import React, { useState, useEffect, useCallback } from 'react';
import {
  View,
  Text,
  StyleSheet,
  SafeAreaView,
  ScrollView,
  TouchableOpacity,
  StatusBar,
  ActivityIndicator,
  RefreshControl,
  Share,
  Alert,
} from 'react-native';
import { useNavigation, useFocusEffect } from '@react-navigation/native';
import type { StackNavigationProp } from '@react-navigation/stack';
import { theme } from '../theme';
import { shoppingListApi } from '../services/inventory.api';
import { ShoppingListItem } from '../types/inventory';

export const ShoppingListScreen: React.FC = () => {
  const navigation = useNavigation<StackNavigationProp<any>>();
  const [shoppingItems, setShoppingItems] = useState<ShoppingListItem[]>([]);
  const [loading, setLoading] = useState(true);
  const [refreshing, setRefreshing] = useState(false);
  const [error, setError] = useState<string | null>(null);

  // Fetch shopping list data
  const fetchShoppingList = async () => {
    try {
      setError(null);
      console.log('🛒 [ShoppingList] Fetching shopping list...');
      const items = await shoppingListApi.getShoppingListItems();
      console.log('🛒 [ShoppingList] Shopping list received:', items.length, 'items');
      setShoppingItems(items);
    } catch (err: any) {
      console.error('❌ [ShoppingList] Error fetching shopping list:', err);
      let errorMessage;

      if (err.statusCode === 0) {
        errorMessage = 'Cannot connect to server. Make sure the backend is running on http://localhost:3001';
      } else if (err.statusCode === 401) {
        errorMessage = 'Session expired. Please restart the app or re-login.';
      } else {
        errorMessage = err.message || 'Failed to load shopping list';
      }

      setError(errorMessage);
    } finally {
      setLoading(false);
      setRefreshing(false);
    }
  };

  // Fetch on mount and when screen comes into focus
  useFocusEffect(
    useCallback(() => {
      fetchShoppingList();
    }, [])
  );

  // Pull to refresh handler
  const onRefresh = useCallback(() => {
    setRefreshing(true);
    fetchShoppingList();
  }, []);

  // Export shopping list
  const handleExport = async () => {
    if (shoppingItems.length === 0) {
      Alert.alert('Empty List', 'Your shopping list is empty. There is nothing to export.');
      return;
    }

    try {
      // Format shopping list as text
      let exportText = '🛒 WeAreOut Shopping List\n\n';

      const urgentItems = shoppingItems.filter(item => item.priority === 'urgent' || item.priority === 'critical');
      const lowItems = shoppingItems.filter(item => item.priority === 'low');

      if (urgentItems.length > 0) {
        exportText += '⚠️ URGENT - OUT SOON:\n';
        urgentItems.forEach(item => {
          exportText += `  • ${item.itemName} - ${item.quantity} ${item.unit}\n`;
        });
        exportText += '\n';
      }

      if (lowItems.length > 0) {
        exportText += '📦 RUNNING LOW:\n';
        lowItems.forEach(item => {
          exportText += `  • ${item.itemName} - ${item.quantity} ${item.unit}\n`;
        });
      }

      exportText += `\n✨ Generated by WeAreOut on ${new Date().toLocaleDateString()}`;

      // Share the list
      await Share.share({
        message: exportText,
        title: 'Shopping List',
      });
    } catch (error: any) {
      console.error('❌ [ShoppingList] Error exporting:', error);
      if (error.message !== 'User did not share') {
        Alert.alert('Export Failed', 'Failed to export shopping list. Please try again.');
      }
    }
  };

  // Group items by priority
  const urgentItems = shoppingItems.filter(item => item.priority === 'urgent' || item.priority === 'critical');
  const lowItems = shoppingItems.filter(item => item.priority === 'low');

  const renderShoppingItem = (item: ShoppingListItem) => {
    const isUrgent = item.priority === 'urgent' || item.priority === 'critical';
    const backgroundColor = isUrgent
      ? theme.colors.critical.background
      : theme.colors.low.background;
    const textColor = isUrgent
      ? theme.colors.critical.dark
      : theme.colors.low.dark;

    return (
      <View key={item.id} style={[styles.itemCard, { backgroundColor }]}>
        <View style={styles.itemHeader}>
          <Text style={styles.itemName}>{item.itemName}</Text>
          <Text style={styles.itemStore}>{item.store || 'Grocery Store'}</Text>
        </View>

        <View style={styles.itemLocation}>
          <Text style={styles.locationIcon}>📍</Text>
          <Text style={styles.locationText}>{item.location || item.notes || 'No location specified'}</Text>
        </View>

        <View style={styles.itemFooter}>
          <Text style={styles.currentStock}>
            Qty needed: {item.quantity} {item.unit}
          </Text>
          <View style={styles.daysLeftBadge}>
            <Text style={[styles.daysLeftText, { color: textColor }]}>
              {isUrgent ? 'Urgent' : 'Low stock'}
            </Text>
          </View>
        </View>
      </View>
    );
  };

  return (
    <View style={styles.container}>
      <StatusBar barStyle="dark-content" />

      <SafeAreaView style={styles.safeArea} edges={['top']}>
        {/* Header */}
        <View style={styles.header}>
          <TouchableOpacity
            style={styles.backButton}
            onPress={() => navigation.goBack()}
            activeOpacity={0.7}
          >
            <Text style={styles.backIcon}>‹</Text>
          </TouchableOpacity>
          <Text style={styles.headerTitle}>Shopping List</Text>
          <TouchableOpacity
            style={styles.exportButton}
            activeOpacity={0.7}
            onPress={handleExport}
          >
            <Text style={styles.exportText}>Export</Text>
          </TouchableOpacity>
        </View>

        <ScrollView
          style={styles.scrollView}
          showsVerticalScrollIndicator={false}
          refreshControl={
            <RefreshControl refreshing={refreshing} onRefresh={onRefresh} />
          }
        >
          {loading && !refreshing ? (
            <View style={styles.loadingContainer}>
              <ActivityIndicator size="large" color={theme.colors.primary[500]} />
              <Text style={styles.loadingText}>Loading shopping list...</Text>
            </View>
          ) : error ? (
            <View style={styles.emptyContainer}>
              <Text style={styles.emptyIcon}>⚠️</Text>
              <Text style={styles.emptyTitle}>Connection Error</Text>
              <Text style={styles.emptySubtitle}>{error}</Text>
              <TouchableOpacity
                style={styles.retryButton}
                onPress={() => fetchShoppingList()}
                activeOpacity={0.7}
              >
                <Text style={styles.retryButtonText}>Retry</Text>
              </TouchableOpacity>
            </View>
          ) : shoppingItems.length === 0 ? (
            <View style={styles.emptyContainer}>
              <Text style={styles.emptyIcon}>🛒</Text>
              <Text style={styles.emptyTitle}>Shopping list is empty</Text>
              <Text style={styles.emptySubtitle}>
                Items that are running low will appear here automatically
              </Text>
            </View>
          ) : (
            <>
              {/* Urgent Section */}
              {urgentItems.length > 0 && (
                <View style={styles.section}>
                  <View style={styles.sectionHeader}>
                    <View style={styles.sectionTitleRow}>
                      <View style={styles.urgentDot} />
                      <Text style={styles.sectionTitle}>Urgent - Out Soon</Text>
                    </View>
                    <Text style={styles.sectionCount}>({urgentItems.length})</Text>
                  </View>
                  {urgentItems.map(renderShoppingItem)}
                </View>
              )}

              {/* Running Low Section */}
              {lowItems.length > 0 && (
                <View style={styles.section}>
                  <View style={styles.sectionHeader}>
                    <View style={styles.sectionTitleRow}>
                      <View style={styles.lowDot} />
                      <Text style={styles.sectionTitle}>Running Low</Text>
                    </View>
                    <Text style={styles.sectionCount}>({lowItems.length})</Text>
                  </View>
                  {lowItems.map(renderShoppingItem)}
                </View>
              )}

              {/* Suggested Shopping Trips */}
              {shoppingItems.length > 0 && (
                <View style={styles.suggestedSection}>
                  <Text style={styles.suggestedTitle}>Suggested Shopping Trips</Text>
                  <View style={styles.suggestedCard}>
                    <View style={styles.suggestedContent}>
                      <Text style={styles.suggestedStoreName}>Grocery Store</Text>
                      <Text style={styles.suggestedItemCount}>{shoppingItems.length} items</Text>
                    </View>
                    <Text style={styles.chevron}>›</Text>
                  </View>
                </View>
              )}
            </>
          )}

          <View style={styles.bottomPadding} />
        </ScrollView>
      </SafeAreaView>
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme.colors.background,
  },
  safeArea: {
    flex: 1,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: theme.spacing[4],
    paddingVertical: theme.spacing[4],
    borderBottomWidth: 1,
    borderBottomColor: theme.colors.border,
  },
  backButton: {
    width: 44,
    height: 44,
    alignItems: 'center',
    justifyContent: 'center',
  },
  backIcon: {
    fontSize: 32,
    color: theme.colors.text.primary,
    fontWeight: '300',
  },
  headerTitle: {
    ...theme.typography.styles.h4,
  },
  exportButton: {
    paddingHorizontal: theme.spacing[4],
    paddingVertical: theme.spacing[2],
  },
  exportText: {
    ...theme.typography.styles.body,
    color: theme.colors.primary[500],
    fontWeight: theme.typography.fontWeight.medium,
  },
  scrollView: {
    flex: 1,
  },
  section: {
    marginTop: theme.spacing[6],
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: theme.spacing[6],
    marginBottom: theme.spacing[4],
  },
  sectionTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: theme.spacing[2],
  },
  urgentDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: theme.colors.critical.DEFAULT,
  },
  lowDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: theme.colors.low.DEFAULT,
  },
  sectionTitle: {
    ...theme.typography.styles.h4,
  },
  sectionCount: {
    ...theme.typography.styles.body,
    color: theme.colors.text.secondary,
  },
  itemCard: {
    marginHorizontal: theme.spacing[6],
    marginBottom: theme.spacing[3],
    padding: theme.spacing[5],
    borderRadius: theme.borderRadius.xl,
  },
  itemHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: theme.spacing[3],
  },
  itemName: {
    ...theme.typography.styles.h4,
    flex: 1,
  },
  itemStore: {
    ...theme.typography.styles.caption,
    color: theme.colors.text.secondary,
  },
  itemLocation: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: theme.spacing[2],
    marginBottom: theme.spacing[3],
  },
  locationIcon: {
    fontSize: 14,
  },
  locationText: {
    ...theme.typography.styles.caption,
    color: theme.colors.text.secondary,
  },
  itemFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  currentStock: {
    ...theme.typography.styles.body,
    color: theme.colors.text.secondary,
  },
  daysLeftBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: theme.spacing[1],
  },
  clockIcon: {
    fontSize: 14,
  },
  daysLeftText: {
    ...theme.typography.styles.caption,
    fontWeight: theme.typography.fontWeight.medium,
  },
  suggestedSection: {
    marginTop: theme.spacing[6],
    paddingHorizontal: theme.spacing[6],
  },
  suggestedTitle: {
    ...theme.typography.styles.h4,
    marginBottom: theme.spacing[4],
  },
  suggestedCard: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: theme.spacing[5],
    backgroundColor: theme.colors.gray[50],
    borderRadius: theme.borderRadius.xl,
    borderWidth: 1,
    borderColor: theme.colors.border,
  },
  suggestedContent: {
    flex: 1,
  },
  suggestedStoreName: {
    ...theme.typography.styles.bodySemibold,
    marginBottom: theme.spacing[1],
  },
  suggestedItemCount: {
    ...theme.typography.styles.caption,
    color: theme.colors.text.secondary,
  },
  chevron: {
    fontSize: 24,
    color: theme.colors.gray[400],
    fontWeight: '300',
  },
  bottomPadding: {
    height: 40,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: theme.spacing[10],
  },
  loadingText: {
    ...theme.typography.styles.body,
    color: theme.colors.text.secondary,
    marginTop: theme.spacing[4],
  },
  emptyContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: theme.spacing[10],
    paddingHorizontal: theme.spacing[6],
  },
  emptyIcon: {
    fontSize: 64,
    marginBottom: theme.spacing[4],
  },
  emptyTitle: {
    ...theme.typography.styles.h3,
    color: theme.colors.text.primary,
    marginBottom: theme.spacing[2],
    textAlign: 'center',
  },
  emptySubtitle: {
    ...theme.typography.styles.body,
    color: theme.colors.text.secondary,
    textAlign: 'center',
    marginBottom: theme.spacing[6],
  },
  retryButton: {
    paddingHorizontal: theme.spacing[6],
    paddingVertical: theme.spacing[3],
    backgroundColor: theme.colors.primary[500],
    borderRadius: theme.borderRadius.lg,
  },
  retryButtonText: {
    ...theme.typography.styles.bodySemibold,
    color: theme.colors.background,
  },
});
